services:
  app:
    container_name: 'app'
    command: sleep infinity
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/node/work
    ports:
      - "3000:3000"
    depends_on:
      - psql
    user: "node"

  psql:
    container_name: 'psql'
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  mcp:
    container_name: 'mcp'
    command: sleep infinity
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
    volumes:
      - ../mcp:/home/node/work/mcp
    ports:
      - "3001:3001"
    user: "node"

volumes:
  psql: